pipeline {
    agent any
    stages {
        stage("Checkout") {
            steps {
                checkout scm
            }
        }
        stage("Build Frontend") {
            steps {
                dir("Frontend") {
                    sh "npm ci"
                    sh "npm run build"
                }
            }
        }
        stage("Build Docker Image") {
            steps {
                dir("Frontend") {
                    sh "docker build -t hotelrm-frontend:${BUILD_NUMBER} ."
                }
            }
        }
    }
}
